.TH SHRUGAPILLAR 1
.SH NAME
shrugapillar \- generate a shrugapillar for fun!
.SH SYNOPSIS
.B shrugapillar
[\fB\-l\fR \fILENGTH\fR]
[\fB\-c\fR \fICOLOR\fR]
[\fB\-p\fR \fIPROMPT\fR]
.SH DESCRIPTION
.B shrugapillar
is a program made for fun that generates a shrugapillar. If you don't know what a shrugapillar is, either execute the command or look it up! :D
.SH OPTIONS
.TP
.BR \-l " " \fIlength\fR
Set the length of the shrugapillar. Default is 1.
.TP
.BR \-c " " \fIcolor\fR
Set the color of the shrugapillar. White is the default.
.TP
.BR \-p " " \fIprompt\fR
Set the prompt for the body of the shrugapillar.
.TP
.BR \-i " "
Ignore the head, antennae, and bottom
